### ISSUE TITLE
Create Build Summary component (accordion content for Build tab)

### ISSUE THREAD

**Issue by joaobertacchi** [profusion/kernelci-dashboard#71]
Details:
- when the accordion expands, a Show More link is available in the bottom of each item. It navigates to the Build Details Page.
- Build Logs link navigate to the logs instead of showing Logs Component.
- **Show an issues list instead of Errors/Warnings**

![Image](https://github.com/profusion/kernelCI-dashboard/assets/60235/2031313c-0a0c-47cd-a963-53a557bbfcdf)

**Comment by mari1912** [comment]
We should change the order of the content, the chart should be in the left and the files should be on the right
